[phases.setup]
nixPkgs = ["nodejs", "python3Full"]

[phases.install]
cmds = [
    "npm install",
    "cd frontend && npm install",
    "cd backend && pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "npm run build"
]

[start]
cmd = "npm run start" 