[phases.setup]
nixPkgs = ["nodejs", "python311", "gcc"]

[phases.install]
cmds = [
  "npm install",
  "cd frontend && npm install",

  "python3 -m venv /opt/venv",

  "source /opt/venv/bin/activate && pip install --upgrade pip",
  "source /opt/venv/bin/activate && pip install --no-cache-dir -r backend/requirements.txt"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "source /opt/venv/bin/activate && python backend/main.py" 